#include "./utils.dl"

.type AllLogicsCat = Normal{}

.init all_logics = VizComp<AllLogicsCat>

all_logics.show(l) :- CongLogs.dec(l).

all_logics.logic_category(l, $Normal()) :- CongLogs.extends(l, $L("K")).
all_logics.category_name($Normal(), "normal").

.output all_logics.out_node(filename="all_logics/node.csv", rfc4180=true)
.output all_logics.out_category(filename="all_logics/category.csv", rfc4180=true)
.output all_logics.out_edge(filename="all_logics/edge.csv", rfc4180=true)
