#include "./utils.dl"
#include "../properties/approximation.dl"

.init norm_approximation = VizComp<Size>

norm_approximation.show(l) :- CongLogs.extends(l, @logic("K")).

norm_approximation.hide(@logic("Fm")).

norm_approximation.category_name($Finite(), "finite").
norm_approximation.category_name($Exponential(), "exponential").
norm_approximation.category_name($Polynomial(), "polynomial").
norm_approximation.category_name($Constant(), "constant").

norm_approximation.logic_category(l, s) :- Approximation.approximable(l, s).

norm_approximation.implies(s1, s2) :- Approximation.less(s1, s2).



.output norm_approximation.out_node(filename="norm_approximation/node.csv", rfc4180=true)
.output norm_approximation.out_category(filename="norm_approximation/category.csv", rfc4180=true)
.output norm_approximation.out_edge(filename="norm_approximation/edge.csv", rfc4180=true)
