#pragma once

#include "../core/cong_logics.dl"

.comp VizComp<C> {
  .decl logic_category(l : Logic, c : C)
  .decl category_name(c : C, c_name : symbol)
  .decl implies(c1 : C, c2 : C)

  // Specifies, which logics will be shown
  .decl show(l : Logic)
  // Specifies which logics should not be shown
  .decl hide(l : Logic)

  // Output
  .decl out_node(n : symbol)
  out_node(n) :- _show(_, n).

  .decl out_category(n : symbol, c : symbol)
  out_category(n, c_name) :- _show(l, n), category_name(c, c_name),
    logic_category(l, c), !_implied_cat(l, c).

  .decl out_edge(n1 : symbol, n2 : symbol)
  out_edge(n2, n1)
    :- CongLogs.extends(l1, l2), !_extends_trans(l1, l2), l1 != l2,
      _show(l1, n1), _show(l2, n2).

  // Internal

  .decl _show(l : Logic, n : symbol)
  _show(l, n) :- show(l), !hide(l), l = $L(n).

  .decl _extends_trans(l1 : Logic, l3 : Logic)
  _extends_trans(l1, l3) :-
    CongLogs.r_between(l1, l2, l3), _show(l2, _),
    !CongLogs.extends(l2, l1), !CongLogs.extends(l3, l2).

  .decl _implied_cat(l : Logic, c : C)
  _implied_cat(l, c) :- logic_category(l, c2), implies(c2, c).
}
