#pragma once

#include "./compl_classes.dl"
#include "../core/cong_logics.dl"

.comp ComplLogsComp {
  .decl dec_SAT_is_in(l : axiom_set, cc : compl_class)
  ComplClasses.dec_in("SAT_" + l, cc), CongLogs.check(l) :- dec_SAT_is_in(l, cc).

  .decl dec_SAT_is_hard(l : axiom_set, cc : compl_class)
  ComplClasses.dec_hard("SAT_" + l, cc), CongLogs.check(l) :- dec_SAT_is_hard(l, cc).

  .decl SAT_is_in(l : axiom_set, cc : compl_class)
  SAT_is_in(l, cc) :- ComplClasses.is_in("SAT_" + l, cc), CongLogs.is(l).

  .decl SAT_is_hard(l : axiom_set, cc : compl_class)
  SAT_is_hard(l, cc) :- ComplClasses.is_hard("SAT_" + l, cc), CongLogs.is(l).
}

.init ComplLogs = ComplLogsComp


// Facts about complexity of some logics

ComplLogs.dec_SAT_is_hard(l, "coNP") :- CongLogs.is(l).
ComplLogs.dec_SAT_is_hard(l, "PSpace")
  :- CongLogs.is(l), CongLogs.extends("GL", l), CongLogs.extends(l, "K").
ComplLogs.dec_SAT_is_hard(l, "PSpace")
  :- CongLogs.is(l), CongLogs.extends("Grz", l), CongLogs.extends(l, "K").
ComplLogs.dec_SAT_is_hard("EC", "PSpace").
ComplLogs.dec_SAT_is_in(l, "coNP") :- l = "EM"; l = "EMD"; l = "E"; l = "EMP".
ComplLogs.dec_SAT_is_in(l, "PSpace") :- l = "K"; l = "KD"; l = "GL".
