#pragma once
#include "../utils.dl"

// `LogicComp<L, A, D>` - Abstract manager for logics `L` with axioms `A`
// and declaration methods (additional to $DefExt(l, a) and $Least()) `D`
.comp LogicComp<L, A, D> : Declarator<L, Def> {
  .type Def = DefExt{l0 : L, a : A} | Least{} | DefOther{d : D}
  .init ALists = ListsComp<A>
  ALists.kind_name("List of axioms for " + s) :- r_def_kind_name(s).

  .decl ax_name(a : A)
  warnings("No `ax_name`s found for " + kn + ". " +
    "Perhaps, you have not added a rule for this in the instance of `LogicComp`")
      :- !ax_name(_), r_def_kind_name(kn).

  // `w_extension(l, l0, a) => (l = l0 + A)`
  .decl w_extension(l : L, l0 : L, a : A)
  name_def(l, $DefExt(l0, a)) :- w_extension(l, l0, a).

  // `w_ax_implies_over(l0, a1, a2) => (l + a1 ⊢ a2)`
  //
  // This is a short way to say
  //
  // `w_extension(@logic("foo"), l0, a1), proves(@logic("foo"), a2).`
  .decl w_ax_implies_over(l0 : L, a1 : A, a2 : A)

  // `extends(l1, l2) <=> (l1 ⊇ l2)`
  .decl extends(l1 : L, l2 : L)
  // `proves(l, a) <=> (l ⊢ a) <=> (l ∋ a)`
  .decl proves(l : L, a : A)

  // # Computation core. `extends` and `proves` are defined by mutual recursion
  //   using only `w_extension` and `w_ax_implies_over`

  // `extends` is reflexive and transitive
  extends(l, l) :- r_name(l).
  extends(l1, l3) :- extends(l1, l2), extends(l2, l3).
  // connection between`proves` and `extends`
  proves(l, ax) :- extends(l, l0), proves(l0, ax).
  // `w_ax_implies_over` eliminator
  proves(l, ax) :- w_ax_implies_over(l0, ax0, ax), extends(l, l0), proves(l, ax0).
  // `w_extension` eliminator
  extends(l, l0), proves(l, ax) :- w_extension(l, l0, ax).
  extends(l1, l) :- w_extension(l, l0, ax), extends(l1, l0), proves(l1, ax).

  // `r_extension(l, l0, a) <= (l = l0 + A)`
  .decl r_extension(l : L, l0 : L, a : A)
  r_extension(l, l0, a2) :-
    w_extension(l, l0, a1),
    r_ax_implies_over(l, a1, a2),
    r_ax_implies_over(l, a2, a1).
  // (l0 + ax1) + ax2 = (l0 + ax2) + ax1
  r_extension(l, l2, ax1) :-
    r_extension(l, l1, ax2),
    r_extension(l1, l0, ax1),
    r_extension(l2, l0, ax2).

  // `r_ax_implies_over(l0, a1, a2) <= (l + a1 ⊢ a2)`
  .decl r_ax_implies_over(l0 : L, a1 : A, a2 : A)
  r_ax_implies_over(l0, a1, a2) :- w_ax_implies_over(l0, a1, a2).
  r_ax_implies_over(l0, a, a) :- r_name(l0), ax_name(a).
  r_ax_implies_over(l0, a1, a3) :- r_ax_implies_over(l0, a1, a2), r_ax_implies_over(l0, a2, a3).
  r_ax_implies_over(l1, a1, a2) :- r_ax_implies_over(l0, a1, a2), extends(l1, l0).

  // `find_extensions_by_some_of(l0, n)` starts search of extensions of
  // `l0` by axioms from the list with name `n`.
  //
  // To define named list, use `ALists.name_def(n, axs)`
  //
  // To gather results, use `r_extension_by_some_of(l, l0, n)`.
  .decl find_extensions_by_some_of(l0 : L, n : ALists.name)
  _find_extensions_by_some_of(l0, axs) :-
    find_extensions_by_some_of(l0, n), ALists.name_def(n, axs).
  // `r_extension_by_some_of(l, l0, n) <= (l = l0 + Γ)`, where `Γ` is a set of
  // some formulas from the list with name `n`.
  //
  // NB! You should also run `find_extensions_by_some_of(l0, n)` to obtain
  // a meaningful result.
  .decl r_extension_by_some_of(l : L, l0 : L, n : ALists.name)
  r_extension_by_some_of(l, l0, n) :-
    _r_extension_by_some_of(l, l0, axs),
    find_extensions_by_some_of(l0, n),
    ALists.name_def(n, axs).

  .decl _find_extensions_by_some_of(l0 : L, axs : ALists.Ty)

  .decl _r_extension_by_some_of(l : L, l0 : L, axs : ALists.Ty)
  _r_extension_by_some_of(l0, l0, axs) :-
    _find_extensions_by_some_of(l0, axs).
  _r_extension_by_some_of(l, l0, axs) :-
    // strictly speaking, we could use `axs \ a` instead of `axs` here
    _r_extension_by_some_of(l1, l0, axs),
    ALists.member(a, axs),
    r_extension(l, l1, a).

  // `r_equiv(l1, l2) <=> l1 = l2` as sets of theorems.
  .decl r_equiv(l1 : L, l2 : L)
  r_equiv(l1, l2) :- extends(l1, l2), extends(l2, l1).

  // `r_between(l0, l1, l2) <=> l0 ⊇ l1 ⊇ l2`
  .decl r_between(l0 : L, l1 : L, l2 : L)
  r_between(l0, l1, l2) :- extends(l0, l1), extends(l1, l2).

  // `fin_axiomatizable(l) <=> l` is finitely axiomatizable (is the least logic
  // containing some finite set of formulas).
  .decl fin_axiomatizable(l : L)
  fin_axiomatizable(l) :- w_extension(l, l0, _), fin_axiomatizable(l0).
}
