#pragma once
#include "../utils.dl"

// Formula in string representation
.type formula <: symbol
// Axiom name wrapped in ADT
.type Axiom = A { ax_name : symbol }

.comp AxiomsComp {
  .decl dec(ax : Axiom, f : formula)
  errors("Axiom declared twice: " + n)
    :- dec(ax, f1), dec(ax, f2), f1 != f2, ax = $A(n).

  .decl is(ax : Axiom)
  .output is(filename="declared/$A.csv")
  is(ax) :- dec(ax, _).

  .decl is_alt(ax : Axiom, n : unsigned)
}

.init Axioms = AxiomsComp

.decl _axiom_dec(ax : symbol, f : formula)
.input _axiom_dec(filename="core/axiom_formula.csv", rfc4180=true, headers=true)
Axioms.dec($A(ax), f) :- _axiom_dec(ax, f).

Axioms.is_alt($A("Alt₁"), 1).
Axioms.is_alt($A("Alt₂"), 2).
