#pragma once
#include "../utils.dl"

// Formula in string representation
.type formula <: symbol
.type axiom <: symbol
.functor axiom(s : symbol) : axiom

.init AxLists = ListsComp<axiom>
AxLists.kind_name("Axioms list").

.comp AxiomsComp : Declarator<axiom, formula> {
  kind_name("Axiom").
  .output r_name(filename="declared/axiom.csv")

  .decl subframe_hereditary(ax : axiom)
  .decl cofinal_subframe_hereditary(ax : axiom)
  cofinal_subframe_hereditary(ax) :- subframe_hereditary(ax).

  .decl alt(ax : axiom, n : unsigned)
  .decl bd(ax : axiom, n : unsigned)
  .decl bw(ax : axiom, n : unsigned)
}

.init Axioms = AxiomsComp

.decl _axioms(ax : symbol, is_subframe_hereditary : symbol, f : formula)
.input _axioms(filename="core/axioms.csv", rfc4180=true, headers=true)
Axioms.name_def(@axiom(ax), f) :- _axioms(ax, _, f).
Axioms.subframe_hereditary(@axiom(ax)) :- _axioms(ax, "yes", _).
Axioms.cofinal_subframe_hereditary(@axiom(ax)) :- _axioms(ax, "cofinal", _).
Axioms.subframe_hereditary(ax)
  :- Axioms.alt(ax, _), Axioms.bd(ax, _), Axioms.bw(ax, _).

Axioms.alt(@axiom("Alt₁"), 1).
Axioms.alt(@axiom("Alt₂"), 2).

Axioms.bd(@axiom("Bd₁"), 1).
Axioms.bd(@axiom("Bd₂"), 2).

Axioms.bw(@axiom("Bw₁"), 1).
Axioms.bw(@axiom("Bw₂"), 1).
