#pragma once

#include "./axioms.dl"
#include "./abstract_logic.dl"

.type logic <: symbol
.functor logic(s : symbol) : logic

.comp CongLogsComp : LogicComp<logic, axiom, Void>{
  .output r_name(filename="declared/logic.csv")

  .decl subframe_hereditary(l : logic)
  subframe_hereditary(l) :- r_extension(l, l0, ax),
    subframe_hereditary(l0), Axioms.subframe_hereditary(ax).
  subframe_hereditary(@logic("K")).
  .decl cofinal_subframe_hereditary(l : logic)
  cofinal_subframe_hereditary(l) :- r_extension(l, l0, ax),
    cofinal_subframe_hereditary(l0), Axioms.cofinal_subframe_hereditary(ax).
  cofinal_subframe_hereditary(l) :- subframe_hereditary(l).
}

.init CongLogs = CongLogsComp
CongLogs.kind_name("Congruential logic").
CongLogs.ax_name(ax) :- Axioms.r_name(ax).

.decl _ext(l : symbol, l0 : symbol, ax : symbol)
.input _ext(filename="core/cong_ext.csv", rfc4180=true, headers=true)
CongLogs.w_extension(@logic(l), @logic(l0), @axiom(ax)) :- _ext(l, l0, ax).

.decl _proves(l : symbol, ax : symbol)
.input _proves(filename="core/proves.csv", rfc4180=true, headers=true)
CongLogs.proves(@logic(l), @axiom(ax)) :- _proves(l, ax).

.decl _ax_implies_over(l : symbol, ax1 : symbol, ax2 : symbol)
.input _ax_implies_over(filename="core/ax_implies_over.csv", rfc4180=true, headers=true)
CongLogs.w_ax_implies_over(@logic(l), @axiom(ax1), @axiom(ax2)) :- _ax_implies_over(l, ax1, ax2).

// Extra declarations

CongLogs.name_def(@logic("E"), $CongLogs.Least()).
CongLogs.fin_axiomatizable(@logic("E")).

CongLogs.proves(@logic("Fm"), ax) :- Axioms.r_name(ax).

CongLogs.w_ax_implies_over(@logic("E"), ax1, ax2)
  :- Axioms.alt(ax1, n1), Axioms.alt(ax2, n2), n1 < n2.

// Extra checks

warnings("Two logics are equal: " + l1 + ", " + l2)
  :- l1 != l2, CongLogs.r_equiv(l1, l2).

// Makinson's theorem: for every logic Λ ⊇ K one of the following holds:
//   - Λ ⊆ Triv
//   - Λ ⊆ Ver
//   - Λ |- ⊥
warnings("Unable to check Makinson's theorem for the logic " + l)
  :- CongLogs.extends(l, @logic("K")),
      !CongLogs.extends(@logic("Triv"), l), !CongLogs.extends(@logic("Ver"), l),
      !CongLogs.proves(l, @axiom("Contr")).
