#pragma once

#include "./axioms.dl"

// Logic name wrapped in ADT
.type Logic = L { l_name : symbol }

.comp CongLogsComp {
  .decl dec(l : Logic)
  .output dec(filename="declared/$L.csv")

  .decl ext(l : Logic, l0 : Logic, ax : Axiom)
  dec(l) :- ext(l, _, _).
  errors("Logic declared twice: " + l)
    :- ext($L(l), l01, ax1), ext($L(l), l02, ax2), (l01 != l02 ; ax1 != ax2).

  .decl ax_implies_over(l : Logic, ax1 : Axiom, ax2 : Axiom)
  ax_implies_over(l, ax1, ax3) :- ax_implies_over(l, ax1, ax2), ax_implies_over(l, ax2, ax3).
  ax_implies_over(l, ax1, ax2) :- ax_implies_over(l0, ax1, ax2), extends(l, l0).

  .decl r_ax_equiv_over(l : Logic, ax1 : Axiom, ax2 : Axiom)
  r_ax_equiv_over(l, ax1, ax2) :- ax_implies_over(l, ax1, ax2), ax_implies_over(l, ax2, ax1).
  r_ax_equiv_over(l, ax, ax) :- dec(l), Axioms.dec(ax).

  .decl r_extension(l : Logic, l0 : Logic, ax : Axiom)
  r_extension(l, l0, ax1) :- ext(l, l0, ax2), r_ax_equiv_over(l0, ax1, ax2).
  // (l0 + ax1) + ax2 = (l0 + ax2) + ax1
  r_extension(l, l2, ax1) :-
    r_extension(l, l1, ax2),
    r_extension(l1, l0, ax1),
    r_extension(l2, l0, ax2).

  .decl _r_extension_by_some_of(l : Logic, l0 : Logic, axs : AxList)
  _r_extension_by_some_of(l, l, axs) :- dec(l), Axioms.dec_list(axs).
  _r_extension_by_some_of(l, l0, axs) :- Axioms.dec_list(axs), axs = [ax, axs1],
    r_extension(l, l1, ax), _r_extension_by_some_of(l1, l0, axs1).
  _r_extension_by_some_of(l, l0, axs) :- Axioms.dec_list(axs), axs = [_, axs1],
    _r_extension_by_some_of(l, l0, axs1).
  .decl r_extension_by_some_of(l : Logic, l0 : Logic, axs : axListName)
  r_extension_by_some_of(l, l0, name)
    :- _r_extension_by_some_of(l, l0, axs), Axioms.named_list(axs, name).

  .decl r_equiv(l1 : Logic, l2 : Logic)
  r_equiv(l1, l2) :- extends(l1, l2), extends(l2, l1).

  .decl r_between(l_upper : Logic, l : Logic, l_lower : Logic)
  r_between(l_upper, l, l_lower) :- extends(l_upper, l), extends(l, l_lower).

  .decl extends(l1 : Logic, l2 : Logic)
  .decl proves(l : Logic, ax : Axiom)

  extends(l, l) :- dec(l).
  extends(l1, l3) :- extends(l1, l2), extends(l2, l3).

  proves(l, ax) :- extends(l, l0), proves(l0, ax).
  proves(l, ax) :- ax_implies_over(l0, ax0, ax), extends(l, l0), proves(l, ax0).

  extends(l, l0), proves(l, ax) :- ext(l, l0, ax).
  extends(l1, l) :- ext(l, l0, ax), extends(l1, l0), proves(l1, ax).
}

.init CongLogs = CongLogsComp

.decl _ext(l : symbol, l0 : symbol, ax : symbol)
.input _ext(filename="core/cong_ext.csv", rfc4180=true, headers=true)
CongLogs.ext($L(l), $L(l0), $A(ax)) :- _ext(l, l0, ax).

.decl _proves(l : symbol, ax : symbol)
.input _proves(filename="core/proves.csv", rfc4180=true, headers=true)
CongLogs.proves($L(l), $A(ax)) :- _proves(l, ax).

.decl _ax_implies_over(l : symbol, ax1 : symbol, ax2 : symbol)
.input _ax_implies_over(filename="core/ax_implies_over.csv", rfc4180=true, headers=true)
CongLogs.ax_implies_over($L(l), $A(ax1), $A(ax2)) :- _ax_implies_over(l, ax1, ax2).

// Extra declarations

CongLogs.dec($L("E")).

CongLogs.proves($L("Fm"), ax) :- Axioms.dec(ax).

CongLogs.ax_implies_over($L("E"), ax1, ax2)
  :- Axioms.alt(ax1, n1), Axioms.alt(ax2, n2), n1 < n2.

// Extra checks

warnings("Two logics are equal: " + n1 + ", " + n2)
  :- CongLogs.dec(l1), CongLogs.dec(l2),
    l1 != l2, CongLogs.r_equiv(l1, l2), l1=$L(n1), l2=$L(n2).

// Makinson's theorem: for every logic Λ ⊇ K one of the following holds:
//   - Λ ⊆ Triv
//   - Λ ⊆ Ver
//   - Λ |- ⊥
warnings("Unable to check Makinson's theorem for the logic " + n)
  :- CongLogs.dec(l), CongLogs.extends(l, $L("K")),
      !CongLogs.extends($L("Triv"), l), !CongLogs.extends($L("Ver"), l),
      !CongLogs.proves(l, $A("Contr")),
      l = $L(n).
