#pragma once
#include "../utils.dl"

.comp LanguageComp<DA, DL> {
  .decl language_name(s : symbol)
  .decl r_def_language_name(s : symbol)
  r_def_language_name(s) :- language_name(s); !language_name(_), s = "unknown".
  warnings("Language component has no language_name") :- !language_name(_).


  .type axiom <: symbol
  .init Axioms = AxiomsComp<DA>
  Axioms.kind_name(s + " axiom") :- r_def_language_name(s).

  .init ALists = ListsComp<axiom>
  ALists.kind_name("list of " + s + " axioms") :- r_def_language_name(s).

  .type logic <: symbol
  .init Logics = LogicsComp<DL>
  Logics.kind_name(s + " logic") :- r_def_language_name(s).

  .comp AxiomsComp<DA> : Declarator<axiom, DA> {
  }

  .comp LogicsComp<DL> : Declarator<logic, Def> {
    .type Def = DefExt{l0 : logic, a : axiom} | Least{} | DefOther{d : DL}

    // `w_extension(l, l0, a) => (l = l0 + axiom)`
    .decl w_extension(l : logic, l0 : logic, a : axiom)
    name_def(l, $DefExt(l0, a)) :- w_extension(l, l0, a).

    // `w_ax_implies_over(l0, a1, a2) => (l + a1 ⊢ a2)`
    //
    // This is a short way to say
    //
    // `w_extension(@logic("foo"), l0, a1), proves(@logic("foo"), a2).`
    .decl w_ax_implies_over(l0 : logic, a1 : axiom, a2 : axiom)

    // `extends(l1, l2) <=> (l1 ⊇ l2)`
    .decl extends(l1 : logic, l2 : logic)
    // `proves(l, a) <=> (l ⊢ a) <=> (l ∋ a)`
    .decl proves(l : logic, a : axiom)

    // # Computation core. `extends` and `proves` are defined by mutual recursion
    //   using only `w_extension` and `w_ax_implies_over`

    // `extends` is reflexive and transitive
    extends(l, l) :- r_name(l).
    extends(l1, l3) :- extends(l1, l2), extends(l2, l3).
    // connection between`proves` and `extends`
    proves(l, ax) :- extends(l, l0), proves(l0, ax).
    // `w_ax_implies_over` eliminator
    proves(l, ax) :- w_ax_implies_over(l0, ax0, ax), extends(l, l0), proves(l, ax0).
    // `w_extension` eliminator
    extends(l, l0), proves(l, ax) :- w_extension(l, l0, ax).
    extends(l1, l) :- w_extension(l, l0, ax), extends(l1, l0), proves(l1, ax).

    // `r_extension(l, l0, a) <= (l = l0 + a)`
    .decl r_extension(l : logic, l0 : logic, a : axiom)
    r_extension(l, l0, a2) :-
      w_extension(l, l0, a1),
      r_ax_implies_over(l, a1, a2),
      r_ax_implies_over(l, a2, a1).
    // (l0 + ax1) + ax2 = (l0 + ax2) + ax1
    r_extension(l, l2, ax1) :-
      r_extension(l, l1, ax2),
      r_extension(l1, l0, ax1),
      r_extension(l2, l0, ax2).

    // `r_ax_implies_over(l0, a1, a2) <= (l + a1 ⊢ a2)`
    .decl r_ax_implies_over(l0 : logic, a1 : axiom, a2 : axiom)
    r_ax_implies_over(l0, a1, a2) :- w_ax_implies_over(l0, a1, a2).
    r_ax_implies_over(l0, a, a) :- r_name(l0), Axioms.r_name(a).
    r_ax_implies_over(l0, a1, a3) :- r_ax_implies_over(l0, a1, a2), r_ax_implies_over(l0, a2, a3).
    r_ax_implies_over(l1, a1, a2) :- r_ax_implies_over(l0, a1, a2), extends(l1, l0).

    .type extensions_by_some_of_id <: symbol
    // `find_extensions_by_some_of(l0, axs, id)` starts search of extensions of
    // `l0` by axioms from `axs` and attaches `id` to this operation.
    //
    // To gather results, use `r_extension_by_some_of(l, id)`.
    .decl find_extensions_by_some_of(l0 : logic, axs : ALists.Ty, id : extensions_by_some_of_id)
    _find_extensions_by_some_of(l0, axs), ALists.def(axs) :-
      find_extensions_by_some_of(l0, axs, _).
    // `r_extension_by_some_of(l, id) <= (l = l0 + Γ)`, where `Γ` is a set of
    // some formulas from `xs`, `l0` and `xs` being that from
    // `find_extensions_by_some_of(l0, axs, id)`.
    .decl r_extension_by_some_of(l : logic, id : extensions_by_some_of_id)
    r_extension_by_some_of(l, id) :-
      _r_extension_by_some_of(l, l0, axs),
      find_extensions_by_some_of(l0, axs, id).

    .decl _find_extensions_by_some_of(l0 : logic, axs : ALists.Ty)

    .decl _r_extension_by_some_of(l : logic, l0 : logic, axs : ALists.Ty)
    _r_extension_by_some_of(l0, l0, axs) :-
      _find_extensions_by_some_of(l0, axs).
    _r_extension_by_some_of(l, l0, axs) :-
      // strictly speaking, we could use `axs \ a` instead of `axs` here
      _r_extension_by_some_of(l1, l0, axs),
      ALists.member(a, axs),
      r_extension(l, l1, a).

    // `r_equiv(l1, l2) <=> l1 = l2` as sets of theorems.
    .decl r_equiv(l1 : logic, l2 : logic)
    r_equiv(l1, l2) :- extends(l1, l2), extends(l2, l1).

    // `r_between(l0, l1, l2) <=> l0 ⊇ l1 ⊇ l2`
    .decl r_between(l0 : logic, l1 : logic, l2 : logic)
    r_between(l0, l1, l2) :- extends(l0, l1), extends(l1, l2).

    // `fin_axiomatizable(l) <=> l` is finitely axiomatizable (is the least logic
    // containing some finite set of formulas).
    .decl fin_axiomatizable(l : logic)
    fin_axiomatizable(l) :- w_extension(l, l0, _), fin_axiomatizable(l0).
  }
}
