#pragma once
#include "../core/cong_logics.dl"

.type Size = Finite{} | Exponential{} | Polynomial{} | Constant{}

.comp ApproximationComp {
  .decl less(s1 : Size, s2 : Size)
  less($Exponential(), $Finite()).
  less($Polynomial(), $Exponential()).
  less($Constant(), $Polynomial()).

  .decl tabular(l : Logic)
  tabular(l) :- approximable(l, $Constant()).
  approximable(l, $Constant()) :- tabular(l).

  .decl fmp(l : Logic)
  fmp(l) :- approximable(l, $Finite()).
  approximable(l, $Finite()) :- fmp(l).

  .decl approximable(l : Logic, s : Size)
  approximable(l, s2) :- approximable(l, s1), less(s1, s2).
}

.init Approximation = ApproximationComp

// ChZa Theorem 18.14
Approximation.approximable(l, $Polynomial()) :- CongLogs.extends(l, $L("S4.3")).
// ChZa Theorem 18.12
Approximation.approximable(l, $Polynomial())
  :- CongLogs.r_extension(l, l0, bd), Axioms.bd(bd, _),
    (l0 = $L("K4"); l0 = $L("S4"); l0 = $L("Grz"); l0 = $L("GL")).
// ChZa Theorem 18.13
Approximation.approximable(l, $Polynomial())
  :- CongLogs.r_extension(l, l0, bw), Axioms.bw(bw, _),
    (l0 = $L("K4"); l0 = $L("S4"); l0 = $L("Grz"); l0 = $L("GL")).
// Every extension of a tabular logic is tabular
Approximation.tabular(l) :- Approximation.tabular(l0), CongLogs.extends(l, l0).
// KTᵈ is the logic of {◯, ⬤}
Approximation.tabular($L("KTᵈ")).
// Generalization of Fine's theorem http://doi.org/10.1215/00294527-1306190
Approximation.fmp(l)
  :- CongLogs.extends(l, $L("wK4")),
    CongLogs.cofinal_subframe_hereditary(l).
