#include "../core/cong_logics.dl"

.type CompC = P {} | NP {} | coNP {} | PSpace {} | ExpTime {} | ExpSpace {} | Decidable {}

.comp ComplexityComp<T> {
  .decl in(t : T, cc : CompC)
  .decl hard(t : T, cc : CompC)
  .decl check(t :T)

  .comp R<T> {
    .decl less(cc1 : CompC, cc2 : CompC)
    .decl complete(t : T, cc : CompC)

    less($P(), $NP()).
    less($P(), $coNP()).
    less($NP(), $PSpace()).
    less($coNP(), $PSpace()).
    less($PSpace(), $ExpTime()).
    less($ExpTime(), $ExpSpace()).
    less($ExpSpace(), $Decidable()).
    less(cc1, cc3) :- less(cc1, cc2), less(cc2, cc3).

    in(t, cc2) :- in(t, cc1), less(cc1, cc2).
    hard(t, cc1) :- hard(t, cc2), less(cc1, cc2).

    complete(t, cc) :- in(t, cc), hard(t, cc).
  }
  .init r = R<T>

  check(t) :- in(t, _); hard(t, _).
}

.type Task = SAT { l : axiom_set }

.init Complexity = ComplexityComp<Task>

CongLogs.check(l) :- Complexity.check($SAT(l)).

Complexity.hard($SAT(l), $coNP()) :- CongLogs.is(l).
Complexity.hard($SAT(l), $PSpace())
  :- CongLogs.is(l), CongLogs.extends("GL", l), CongLogs.extends(l, "K").
Complexity.hard($SAT(l), $PSpace())
  :- CongLogs.is(l), CongLogs.extends("Grz", l), CongLogs.extends(l, "K").
Complexity.hard($SAT("EC"), $PSpace()).
Complexity.in($SAT(l), $coNP()) :- l = "EM"; l = "EMD"; l = "E"; l = "EMP".
Complexity.in($SAT(l), $PSpace()) :- l = "K"; l = "KD"; l = "GL".
