// Formula in string representation
.type formula <: symbol
// Named formula
.type axiom <: symbol
// Set of axioms
.type axiom_set <: symbol
// Source file name
.type src_file <: symbol

.decl errors(source : src_file, what : symbol)
.output errors(IO=stdout)

.decl warnings(source : src_file, what : symbol)
.output warnings(IO=stdout)

.comp InputStage {
  .decl axiom_formula(ax : axiom, f : formula)
  .input axiom_formula(filename="axiom_formula.csv", rfc4180=true)

  .decl check_axiom(ax: axiom, source: src_file)
  errors(src, "Undefined axiom: " + ax) :- check_axiom(ax, src), !axiom_formula(ax, _).

  .decl cong_logic(l : axiom_set)
  cong_logic(l) :- cong_ext(l, _, _).

  .decl check_cong_logic(l: axiom_set, source: src_file)
  errors(src, "Undefined logic: " + l) :- check_cong_logic(l, src), !cong_logic(l).

  .decl cong_ext(l : axiom_set, l0 : axiom_set, ax : axiom)
  .input cong_ext(filename="cong_ext.csv", rfc4180=true)
  check_cong_logic(l0, f), check_axiom(ax, f) :- cong_ext(_, l0, ax), f = "cong_ext.csv".

  .decl proves(l : axiom_set, ax : axiom)
  .input proves(filename="proves.csv", rfc4180=true)
  check_cong_logic(l, f), check_axiom(ax, f)
    :- proves(l, ax), f = "proves.csv".

  .decl ax_implies_over(l : axiom_set, ax1 : axiom, ax2 : axiom)
  .input ax_implies_over(filename="ax_implies_over.csv", rfc4180=true)
  check_cong_logic(l, f), check_axiom(ax1, f), check_axiom(ax2, f)
    :- ax_implies_over(l, ax1, ax2), f = "ax_implies_over.csv".

  .decl hidden_logic(l : axiom_set)
  .input hidden_logic(filename="hidden_logic.csv", rfc4180=true)
  check_cong_logic(l, f) :- hidden_logic(l), f = "hidden_logic.csv".

  cong_logic("E").

  proves("Fm", ax) :- axiom_formula(ax, _).

  .decl ax_alt(ax : axiom, n : unsigned)
  ax_alt("Alt₁", 1).
  ax_alt("Alt₂", 2).
  ax_implies_over("E", ax1, ax2) :- ax_alt(ax1, n1), ax_alt(ax2, n2), n1 < n2.
}

.init Input = InputStage

.comp DeductionStage {
  .decl extends(s1 : axiom_set, s2 : axiom_set)
  extends(s1, s2) :- Input.cong_ext(s1, s2, _).
  extends(s1, s1) :- extends(s1, _).
  extends(s2, s2) :- extends(_, s2).
  extends(s1, s3) :- extends(s1, s2), extends(s2, s3).

  extends(l, l0), proves(l, ax) :- Input.cong_ext(l, l0, ax).
  extends(l1, l) :- Input.cong_ext(l, l0, ax), extends(l1, l0), proves(l1, ax).

  .decl proves(l : axiom_set, ax : axiom)
  proves(l, ax) :- Input.proves(l, ax).
  proves(l, ax) :- extends(l, l0), proves(l0, ax).
  proves(l, ax) :- Input.ax_implies_over(l0, ax0, ax), extends(l, l0), proves(l, ax0).
}

.init Deduction = DeductionStage

.comp PostStage {
  .decl equiv(s1 : axiom_set, s2 : axiom_set)
  equiv(s1, s2) :- Deduction.extends(s1, s2), Deduction.extends(s2, s1).

  errors("", "Two logics are equal but none of them is marked as hidden: " + l1 + ", " + l2)
    :- Input.cong_logic(l1), Input.cong_logic(l2),
      !Input.hidden_logic(l1), !Input.hidden_logic(l2),
      l1 != l2, equiv(l1, l2).

  // Makinson's theorem: for every logic Λ ⊇ K one of the following holds:
  //   - Λ ⊆ Triv
  //   - Λ ⊆ Ver
  //   - Λ |- ⊥
  warnings("", "Unable to check Makinson's theorem for the logic " + l)
    :- Input.cong_logic(l), Deduction.extends(l, "K"),
       !Deduction.extends("Triv", l), !Deduction.extends("Ver", l),
       !Deduction.proves(l,"Contr").
}

.init Post = PostStage
