#pragma once

.decl errors(what : symbol)
.output errors(IO=stdout)

.decl warnings(what : symbol)
.output warnings(IO=stdout)

.decl is_num(n : unsigned)
is_num(0). is_num(1). is_num(2).

.type InfUnsigned = Inf {} | Fin { num : unsigned }

.decl inf_less(n1 : InfUnsigned, n2 : InfUnsigned)
inf_less($Fin(n), $Inf()) :- is_num(n).
inf_less($Fin(n1), $Fin(n2)) :- n1 < n2, is_num(n1), is_num(n2).

// Unknown {} is used for properties which are stated somewhere as open problems
.type Bool3 = True {} | False {} | Unknown {}

.comp Declarator<Ty, Name> {
  .decl kind_name(s : symbol)

  .decl dec(x : Ty)
  .decl named(x : Ty, n : Name)

  dec(x) :- named(x, _).

  errors(kn + " with name '" + n + "' was declared twice")
    :- kind_name(kn), named(x1, n), named(x2, n), x1 != x2.
}

.comp ListsComp<T> : Declarator<Ty, name> {
  kind_name("List").
  .type Ty = [head : T, tail : Ty]
  .type name <: symbol

  dec(xs) :- dec([_, xs]).
}
