#pragma once

.decl errors(what : symbol)
.output errors(IO=stdout)

.decl warnings(what : symbol)
.output warnings(IO=stdout)

.decl is_num(n : unsigned)
is_num(0). is_num(1). is_num(2).

.type InfUnsigned = Inf {} | Fin { num : unsigned }

.decl inf_less(n1 : InfUnsigned, n2 : InfUnsigned)
inf_less($Fin(n), $Inf()) :- is_num(n).
inf_less($Fin(n1), $Fin(n2)) :- n1 < n2, is_num(n1), is_num(n2).

// Unknown {} is used for properties which are stated somewhere as open problems
.type Bool3 = True {} | False {} | Unknown {}

.comp ListsComp<T> {
  .type Ty = [head : T, tail : Ty]
  .type name <: symbol

  .decl dec(xs : Ty)
  dec(xs) :- dec([_, xs]).

  .decl named(xs : Ty, name : name)
  dec(xs) :- named(xs, _).
  errors("List with name '" + name + "' was declared twice")
    :- named(xs1, name), named(xs2, name), xs1 != xs2.
}
