#pragma once

.decl errors(what : symbol)
.output errors(IO=stdout)

.decl warnings(what : symbol)
.output warnings(IO=stdout)

.decl is_num(n : unsigned)
is_num(0). is_num(1). is_num(2).

.type InfUnsigned = Inf {} | Unsigned { num : unsigned }

.decl inf_less(n1 : InfUnsigned, n2 : InfUnsigned)
inf_less($Unsigned(n), $Inf()) :- is_num(n).
inf_less($Unsigned(n1), $Unsigned(n2)) :- n1 < n2, is_num(n1), is_num(n2).

// Unknown {} is used for properties which are stated somewhere as open problems
.type Bool3 = True {} | False {} | Unknown {}
