#include "properties/complexity.dl"
#include "properties/interpolation.dl"

.type color <: symbol

.decl l_color(l : Logic, c : color)
l_color(l, "green") :- Complexity.in($SAT(l, $Inf()), $coNP()).
l_color(l, "yellow") :- Complexity.r_complete($SAT(l, $Inf()), $PSpace()).
l_color(l, "orange")
  :- Complexity.hard($SAT(l, $Inf()), $PSpace()),
    !Complexity.in($SAT(l, $Inf()), $PSpace()).

.decl color_def(l : Logic, c : color)
color_def(l, c) :- l_color(l, c).
color_def(l, "white") :- CongLogs.dec(l), !l_color(l, _).

.decl show(l : Logic, n : symbol)
show(l, n) :- CongLogs.dec(l), l = $L(n), CongLogs.extends(l, $L("K")).

.decl node(n : symbol, c : color)
node(n, c) :- show(l, n), color_def(l, c).
.output node(rfc4180=true)

.decl extends3(c1 : Logic, c2 : Logic, c3 : Logic)
extends3(c1, c2, c3) :- CongLogs.extends(c1, c2), CongLogs.extends(c2, c3), show(c2, _),
  !CongLogs.extends(c2, c1), !CongLogs.extends(c3, c2).

.decl edge(c1 : symbol, c2 : symbol)
edge(n2, n1) :- CongLogs.extends(c1, c2), !extends3(c1, _, c2), show(c1, n1), show(c2, n2), c1 != c2.
.output edge(rfc4180=true)
